language: ruby
rvm:
  - 1.9.3
  - 2.0
  - ruby-head
  - jruby-19mode
  - rbx-2.1.1
  - jruby-head
script: rake test
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-2.1.1
    - rvm: jruby-head
